### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by dxeglow** [st1koo/secure-gamesense-forum#2]
Hello! Im have this error 
![image](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/abb3edcd-17fc-4da8-b7c8-92ae02118dcd)
My 'database.php' file:
![image](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/7159e250-7b00-4937-a2cb-6fd493753932)
My PHP version: 5.6
Im using hosting (not localhost)

**Comment by st1koo** [comment]
you are using the wrong username/or password.
