### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by dxeglow** [st1koo/secure-gamesense-forum#3]
![image](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/6866703b-d116-4a60-a36f-616cb44ad982)
  
![image](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/1defe9c6-bfba-40b0-aec7-8a7df32f1e29)

**Comment by st1koo** [comment]
The password is encrypted so you cant just use a plain password and log in with it. If you dont even know that you shouldn't even try to make a forum with my source.

**Comment by dxeglow** [comment]
> The password is encrypted so you cant just use a plain password and log in with it. If you dont even know that you shouldn't even try to make a forum with my source.

How to decrypt password?
