### ISSUE TITLE
Cant create invition code

### ISSUE THREAD

**Issue by dxeglow** [st1koo/secure-gamesense-forum#4]
![image](https://github.com/st1koo/secure-gamesense-forum/assets/88434607/3bb89d04-4034-4e26-aef0-7b0095c3e643)

**Comment by st1koo** [comment]
Look if you don't know how to deal with a error thats says what you have to do, i wouldn't recommend even trying. But as it says "HTTP_REFERER", that means you will need to clear the cache and then change the base url to your own domain since its trying to use the cached domain right now.
